#!/usr/bin/env python3
"""Hypothesis testing for dynamical invariants.

Script structure
----------------

This file is intentionally organized as a single executable pipeline because it
is called from several Windows batch scripts with different metric scopes. Read
it in the following order:

1. Global configuration and metric registry
   Defines the active embedding dimensions, bootstrap parameters, RQA defaults,
   and the set of metric names accepted by the CLI. This is where methodological
   constants shared with the batch scripts are centralized.

2. Surrogate and reference series generation
   Builds the three non-original comparison series:
   a full reshuffle, Gaussian white noise, and Student-t noise. Stationary
   bootstrap pseudo-series are generated by surrogate_sampling.py and consumed
   later in main().

3. Hypothesis-test helpers
   Implements the active stationary-bootstrap TS decision rule. Historical
   F-test/variance-testing code has been removed from this script.

4. TISEAN wrappers and output parsers
   Resolves and runs d2.exe, c2t.exe, and lyap_k.exe, then parses their text
   output blocks. This section converts command-line tool outputs into numeric
   NumPy arrays used by the invariant extractors.

5. Dimension extractors: TAKENS and ELLNER
   Selects stable scaling/plateau windows. TAKENS is the plateau mean of the
   c2t-produced d_2^(T)(r') curve. ELLNER reuses that plateau interval
   [r_min, r_max] and integrates the .c2 correlation integral over it.

6. Lyapunov and RQA helpers
   Extracts a scalar Kantz largest-Lyapunov estimate from S(t), computes
   percentile-based RQA radii, enforces an effective Theiler window for PyRQA,
   and adds the custom TREND metric.

7. compute_invariants()
   The central dispatcher for one in-memory series. It writes the series to a
   temporary .dat file, runs only the external tools required by the requested
   metrics, and returns estimate/SD/count dictionaries.

8. main()
   The full CLI workflow: load original data, build reference series, compute
   original/reference/bootstrap invariants, calculate TS decisions, and write a
   parser-friendly summary file consumed by print_results.py and documents.py.

Correlation dimension is estimated via Takens' maximum-likelihood estimator
(eq. 8.75-8.76) and its Ellner extension (eq. 8.78):

    1. d2.exe writes the correlation integral C^(m)(r) into a .c2 file (and
       h2 / d2 by-products used elsewhere).
    2. c2t.exe converts .c2 into the Takens-Theiler curve d_2^(T)(r').
    3. A stable plateau in d_2^(T)(r') vs ln r' is detected automatically; the
       plateau end-points yield r_min and r_max.
    4. The Ellner extension d_2^(E) is computed directly from .c2 over
       [r_min, r_max] using equation 8.78.

Both values are kept as separate invariants:
    TAKENS = plateau mean of d_2^(T)(r') from c2t.exe,
    ELLNER = Ellner extension d_2^(E) from .c2 over the same plateau interval.

Current core test for TAKENS/ELLNER/LLE:
    1. Generate B stationary-bootstrap pseudo-series from the original series.
    2. Compute the invariant for each pseudo-series.
    3. Let boot_mean be the arithmetic mean and boot_sd the sample SD of those
       B invariant values.
    4. Compute the same invariant for one fully reshuffled series.
    5. TS = (boot_mean - invariant_reshuffle) / boot_sd.
       Reject H0 for |TS| > 3. This rejects the interpretation that the series
       is only independent random noise; it is evidence of structure/memory as a
       prerequisite for chaos, not a proof of chaos.

Normal and Student-t references are still computed as descriptive benchmarks.
RQA remains a scalar original-series summary without this bootstrap test.
"""
import argparse
import glob
import logging
import os
import shutil
import subprocess
import warnings

import numpy as np
from scipy.spatial.distance import pdist
from pyrqa.analysis_type import Classic
from pyrqa.computation import RQAComputation
from pyrqa.metric import EuclideanMetric
from pyrqa.neighbourhood import FixedRadius
from pyrqa.settings import Settings
from pyrqa.time_series import TimeSeries

warnings.filterwarnings("ignore", category=RuntimeWarning)
warnings.filterwarnings("ignore", category=UserWarning)

from surrogate_sampling import load_series_1d, stationary_bootstrap_samples

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Global configuration
# ---------------------------------------------------------------------------
#
# The constants below are intentionally kept near the top of the file because
# they define the methodological contract used by the batch scripts:
#
# * DEFAULT_BOOTSTRAP_SAMPLES controls the number of stationary-bootstrap
#   pseudo-series used to estimate the empirical centre/spread of an invariant.
# * DEFAULT_TS_THRESHOLD is the supervisor-approved "three sigma" decision rule
#   for the bootstrap test statistic.
# * M_D2 and M_LYAP fix the embedding dimension used by the current thesis
#   workflow. The Windows batch files are expected to use matching values.
#
# Keeping these values centralized avoids hidden drift between Python
# recomputation, TISEAN command-line calls, and the generated result summaries.

DEFAULT_BOOTSTRAP_SAMPLES = 100
DEFAULT_TS_THRESHOLD = 3.0
DEFAULT_STATIONARY_BLOCK_MEAN = 0.0  # <=0 means sqrt(n)

# Degrees of freedom for t-distribution reference series
T_DOF = 3.5

# Must match -M1,3 in correlation_dimension.bat
M_D2 = 3
M_LYAP = 3

DEFAULT_RQA_RADIUS = 0.005
RQA_EMBEDDING_DIM = 3

# Percentile-based recurrence threshold (per `rqa_tran.pdf`):
# fix the radius as a quantile of pairwise distances between embedded state
# vectors so the recurrence rate stays roughly invariant across coins,
# embedding dimensions and window lengths. Default 4% ~ RR ~ 4%.
RQA_RADIUS_PERCENTILE_DEFAULT = 4.0
# Embedded matrix is subsampled to this many vectors before pdist to keep
# memory bounded (pdist is O(N^2)). 5000 vectors -> ~12.5M pairs (~100 MB).
RQA_RADIUS_MAX_VECTORS = 5000
RQA_RADIUS_SAMPLE_SEED = 0
D2_EPSILON_STEPS = 100
D2_PAIR_LIMIT = 0
MIN_PLATEAU_POINTS = 8

# The metric registry controls CLI validation, null/reference recomputation, and
# bootstrap testing. Only metrics in BOOTSTRAP_TEST_METRICS get a TS decision.
RQA_KEYS = ("RR", "DET", "LAM", "MAXLINE", "ENTR", "TT", "TREND")
ALL_METRICS = ("TAKENS", "ELLNER", "LLE", *RQA_KEYS)
NULL_SERIES_METRICS = {"TAKENS", "ELLNER", "LLE"}
BOOTSTRAP_TEST_METRICS = {"TAKENS", "ELLNER", "LLE"}

# ---------------------------------------------------------------------------
# Surrogate and reference series generation
# ---------------------------------------------------------------------------
#
# The current test uses exactly one fully reshuffled series as the independent
# noise reference. Gaussian and Student-t series are computed only as descriptive
# benchmarks with the same first two moments as the original log-return series.
# The stationary bootstrap samples are produced in surrogate_sampling.py because
# they are reused as a standalone sampling primitive.

def generate_single_surrogate(data: np.ndarray) -> np.ndarray:
    """Random permutation of the original series (randperm, no blocking).

    This destroys temporal ordering while preserving the empirical marginal
    distribution exactly. It is the "reshuffle" value in the TS denominator.
    """
    return np.random.permutation(data)


def generate_normal_series(mu: float, sigma: float, n: int) -> np.ndarray:
    """Gaussian white-noise reference with the original mean and SD."""
    return np.random.normal(mu, sigma, n)


def generate_t_series(mu: float, sigma: float, n: int, dof: float = T_DOF) -> np.ndarray:
    """t(dof) series scaled to (mu, sigma).

    t(dof) has zero mean and variance dof/(dof-2) for dof>2, so
    scale raw draws by sigma / sqrt(dof/(dof-2)) and shift by mu.
    """
    t_raw = np.random.standard_t(dof, n)
    t_sd = np.sqrt(dof / (dof - 2.0))
    return mu + sigma * (t_raw / t_sd)


# ---------------------------------------------------------------------------
# Hypothesis test helpers
# ---------------------------------------------------------------------------
#
# The current thesis output should be interpreted through
# TS=(boot_mean-reshuffle)/boot_sd with a fixed absolute threshold.

def invariant_bootstrap_ts_test(
    boot_mean: float,
    boot_sd: float,
    resh_value: float,
    threshold: float = DEFAULT_TS_THRESHOLD,
) -> tuple[float, float, str]:
    """TS=(boot_mean-reshuffle)/boot_sd with decision |TS| > threshold.

    The bootstrap distribution represents structured pseudo-series from the
    original data. The reshuffled value represents independent random ordering.
    A large absolute TS means the invariant under structured resampling is far
    from the invariant under full temporal destruction.
    """
    if not (np.isfinite(boot_mean) and np.isfinite(boot_sd) and np.isfinite(resh_value)):
        return np.nan, np.nan, "insufficient data"
    if boot_sd <= 0.0:
        return np.nan, np.nan, "no sd"
    ts = float((boot_mean - resh_value) / boot_sd)
    abs_ts = abs(ts)
    decision = "reject H0" if abs_ts > threshold else "fail to reject H0"
    return ts, abs_ts, decision


# ---------------------------------------------------------------------------
# TISEAN command wrappers and low-level parsers
# ---------------------------------------------------------------------------
#
# This project relies on external TISEAN executables for the heavy nonlinear
# time-series routines. The wrappers below keep all subprocess invocation details
# in one place so higher-level invariant code can work with normal Python files:
#
# * run_d2 writes .d2, .h2 and .c2 outputs from one call.
# * run_c2t transforms the .c2 correlation integral into Takens curves.
# * run_lyap_k writes Kantz S(t) divergence curves for LLE extraction.
#
# Parser helpers are intentionally tolerant: TISEAN files contain metadata lines,
# empty lines, and multiple indexed blocks. When parsing fails, the function
# returns an empty array/NaN and lets the caller mark that invariant unavailable.

def load_data(filename):
    """Load one-column log-return data through the shared sampling helper."""
    return load_series_1d(filename)


def resolve_tool(tool_name):
    """Resolve a TISEAN executable without hard-coding one installation path.

    Resolution order:
      1. TISEAN_BIN environment variable,
      2. repository-local Tisean_3.0.0/bin directory,
      3. PATH lookup, with and without the Windows .exe suffix.

    Keeping this flexible is important because the code is used both from
    Windows batch scripts and from direct Python smoke tests.
    """
    from_env = os.environ.get("TISEAN_BIN")
    if from_env:
        candidate = os.path.join(from_env, f"{tool_name}.exe")
        if os.path.exists(candidate):
            return candidate
    local_bin = os.path.join(
        os.path.dirname(os.path.abspath(__file__)),
        "Tisean_3.0.0", "bin", f"{tool_name}.exe",
    )
    if os.path.exists(local_bin):
        return local_bin
    which = shutil.which(tool_name)
    if which:
        return which
    which_exe = shutil.which(f"{tool_name}.exe")
    if which_exe:
        return which_exe
    raise FileNotFoundError(f"TISEAN executable for '{tool_name}' was not found.")


def run_d2(data_file, delay, theiler, output_prefix, eps_min=None, eps_max=None):
    """Run TISEAN d2.exe. Optional `eps_min`/`eps_max` set `-r` / `-R` scale bounds.

    The default `eps_min` / `eps_max` strategy in this pipeline (see
    `compute_invariants`) is 0.25*sigma .. 0.5*sigma of the analysed series,
    matching the book's practical recommendation for the Takens scale range.
    """
    # `d2.exe` is the common source for the current dimension path:
    # .c2 -> Takens and Ellner dimension estimates,
    # .h2 -> generated by TISEAN but no longer consumed by hypothesis.py,
    # .d2 -> local-slope diagnostic plots only.
    cmd = [resolve_tool("d2"), f"-d{delay}", f"-M1,{M_D2}", f"-t{theiler}",
           f"-#{D2_EPSILON_STEPS}", f"-N{D2_PAIR_LIMIT}"]
    if eps_min is not None and np.isfinite(eps_min) and eps_min > 0.0:
        cmd.append(f"-r{eps_min}")
    if eps_max is not None and np.isfinite(eps_max) and eps_max > 0.0:
        cmd.append(f"-R{eps_max}")
    cmd += ["-o", output_prefix, data_file]
    subprocess.run(cmd, check=True, capture_output=True, text=True)
    return output_prefix + ".d2", output_prefix + ".h2", output_prefix + ".c2"


def run_c2t(c2_file, output_file):
    """Run TISEAN c2t using relative paths to avoid FORTRAN path-length limits."""
    # The Windows TISEAN build uses old FORTRAN fixed-length path buffers.
    # Running from the output directory and passing basenames avoids silent
    # truncation for long thesis result paths.
    #
    # Methodological role:
    # c2t converts the correlation integral C^(m)(r) from .c2 into Takens'
    # maximum-likelihood correlation-dimension curve d_2^(T)(r'), i.e. the
    # practical form of the book's equations (8.75)-(8.76). This script does not
    # implement the all-pairs Takens average directly; it delegates that part to
    # TISEAN and then selects a stable plateau from the resulting curve.
    cwd = os.path.dirname(os.path.abspath(c2_file))
    cmd = [
        resolve_tool("c2t"),
        "-V0",
        "-o",
        os.path.basename(output_file),
        os.path.basename(c2_file),
    ]
    subprocess.run(cmd, cwd=cwd, check=True, capture_output=True, text=True)
    return output_file


def run_lyap_k(data_file, delay, output_file):
    # Kantz / largest-Lyapunov setup:
    #
    # The book motivates the largest Lyapunov exponent through the exponential
    # separation of nearby trajectories (equation 8.94). In reconstructed phase
    # space, lyap_k estimates the averaged logarithmic divergence S(t) from
    # neighbourhoods U_k around randomly selected reference states W (equation
    # 8.95). The exponent is then the slope of the linear part of S(t) vs t.
    #
    # Options used here:
    #   -m3 -M3 : compute only embedding dimension m=3, matching the rest of the
    #             thesis invariant workflow.
    #   -n500   : use about 500 reference states W, consistent with the book's
    #             practical recommendation that |W| around 500 is usually enough.
    #   -s10    : require approximately 10 neighbours in each U_k, matching the
    #             book's recommendation that each reference point should have
    #             several neighbours while keeping neighbourhoods local.
    #
    # We intentionally do not pass a Theiler window to lyap_k here. The Theiler
    # value used for d2/RQA is not automatically equivalent to the exclusion
    # choices for Kantz's method, and keeping this explicit avoids hidden coupling.
    cmd = [resolve_tool("lyap_k"), f"-d{delay}", f"-m{M_LYAP}", f"-M{M_LYAP}",
           "-n", "500", "-s", "10", "-o", output_file, data_file]
    subprocess.run(cmd, check=True, capture_output=True, text=True)


def extract_tagged_block(path, dim=M_D2, tag="#dim"):
    """Read a two-column block identified by '#dim=' or '#m=' from TISEAN outputs.

    TISEAN outputs usually contain several blocks:
      * .c2/.d2/.h2 label embedding blocks as "#dim=<m>",
      * c2t labels Takens blocks as "#m=<m>".

    The first column is always the scale r (or r'), and the second column is the
    metric value at that scale. Higher columns, if present, are ignored here.
    """
    rows = []
    current_dim = None
    try:
        with open(path, "r", encoding="utf-8", errors="ignore") as handle:
            for line in handle:
                stripped = line.strip()
                if not stripped:
                    continue
                if stripped.startswith(tag):
                    try:
                        current_dim = int(stripped.split("=")[1].strip())
                    except (ValueError, IndexError):
                        current_dim = None
                    continue
                if stripped.startswith("#") or stripped.startswith("!"):
                    continue
                if current_dim != dim:
                    continue
                parts = stripped.split()
                if len(parts) < 2:
                    continue
                try:
                    rows.append((float(parts[0]), float(parts[1])))
                except ValueError:
                    continue
    except Exception:
        return np.empty((0, 2), dtype=float)
    return np.array(rows, dtype=float)


def select_plateau_values(rows, min_points=MIN_PLATEAU_POINTS):
    """Select a stable scaling/plateau window from (epsilon, value) rows.

    Returns `(y_values, r_min, r_max)` where `y_values` are the plateau values
    sorted by ln(epsilon) and `r_min`, `r_max` are the epsilon end-points of the
    selected window (in the original linear scale). `r_min` / `r_max` are NaN if
    no usable rows were supplied.
    """
    arr = np.asarray(rows, dtype=float)
    if arr.size == 0 or arr.ndim != 2 or arr.shape[1] < 2:
        return np.array([], dtype=float), np.nan, np.nan

    eps = arr[:, 0]
    values = arr[:, 1]
    mask = np.isfinite(eps) & np.isfinite(values) & (eps > 0.0) & (values > 0.0)
    eps = eps[mask]
    values = values[mask]
    if values.size == 0:
        return np.array([], dtype=float), np.nan, np.nan

    # Sort by log scale because both local slopes and Takens estimates are
    # interpreted visually/methodologically as functions of ln(r).
    order = np.argsort(np.log(eps))
    eps_sorted = eps[order]
    x = np.log(eps_sorted)
    y = values[order]
    n = y.size
    if n < min_points:
        return y, float(eps_sorted[0]), float(eps_sorted[-1])

    # Window scoring favours flat, low-variance, and reasonably long regions.
    #
    # Book connection:
    # After equation (8.77), the text recommends treating d_2^(T)(r') as a
    # function of scale r' and estimating the correlation dimension from a
    # plateau in the graph d_2^(T)(r') versus ln(r'), instead of choosing a single
    # ad hoc r'. This function operationalizes that instruction. The score is
    # deliberately transparent: penalize slope and relative spread, add a small
    # bonus for longer intervals.
    best_score = -np.inf
    best_ij = (0, n)
    for i in range(0, n - min_points + 1):
        for j in range(i + min_points, n + 1):
            xs = x[i:j]
            ys = y[i:j]
            mean_abs = abs(float(np.mean(ys))) + 1e-12
            try:
                slope, _ = np.polyfit(xs, ys, 1)
            except Exception:
                continue
            rel_slope = abs(float(slope)) / mean_abs
            rel_sd = float(np.std(ys, ddof=1)) / mean_abs if ys.size > 1 else np.inf
            length_bonus = (j - i) / n
            score = 0.10 * length_bonus - rel_slope - rel_sd
            if score > best_score:
                best_score = score
                best_ij = (i, j)

    i, j = best_ij
    return y[i:j], float(eps_sorted[i]), float(eps_sorted[j - 1])


def _pearson_abs(x, y):
    """Absolute Pearson correlation with guards for degenerate windows."""
    if len(x) < 2 or len(y) < 2:
        return np.nan
    sx = float(np.std(x, ddof=1))
    sy = float(np.std(y, ddof=1))
    if sx <= 0.0 or sy <= 0.0:
        return np.nan
    return abs(float(np.corrcoef(x, y)[0, 1]))


def _mean_sd_n(values):
    """Return mean, sample SD, and finite-count for an estimator vector."""
    values = np.asarray(values, dtype=float)
    values = values[np.isfinite(values)]
    if values.size == 0:
        return np.nan, np.nan, 0
    mean = float(np.mean(values))
    sd = float(np.std(values, ddof=1)) if values.size > 1 else np.nan
    return mean, sd, int(values.size)


def extract_takens_plateau(takens_file, dim=M_D2):
    """Find a stable plateau on d_2^(T)(r') for embedding m=`dim`.

    Returns `(mean_val, sd_val, n_val, r_min, r_max)`:
      * `mean_val`/`sd_val`/`n_val` summarise the Takens values inside the plateau;
      * `r_min`/`r_max` are the radius end-points of that plateau (eq. 8.78 in the
        book). `r_min`/`r_max` are NaN if no plateau could be found.
    """
    # c2t produces d_2^(T)(r') as a curve:
    #
    #   d_2^(T)(r') = < log(r' / r_ij) >^(-1)                         (8.75)
    #
    # and, equivalently in terms of the correlation integral,
    #
    #   d_2^(T)(r') = C^(m)(r') / integral_0^{r'} C^(m)(r) / r dr       (8.76)
    #
    # The book explicitly notes that r' is a free scale parameter. Rather than
    # fixing a single r' by hand, it recommends computing the full curve and
    # choosing a plateau in d_2^(T)(r') versus ln(r'). That is exactly what
    # select_plateau_values() does below.
    #
    # The returned mean is the standalone TAKENS invariant. The returned r_min
    # and r_max are not arbitrary bounds: they are the selected plateau interval,
    # later reused by compute_ellner_from_c2() for equation (8.78).
    #
    # Note on uncertainty:
    # Equation (8.77) gives a theoretical standard deviation for a single Takens
    # estimate at a fixed r' in terms of the number of close pairs M_C(r'). Here
    # we report the empirical SD of the plateau values instead. That SD is used
    # as an orientation for plateau stability; the formal hypothesis-test SD is
    # computed across the B stationary-bootstrap invariant estimates.
    rows = extract_tagged_block(takens_file, dim=dim, tag="#m")
    if rows.size == 0:
        return np.nan, np.nan, 0, np.nan, np.nan
    y, r_min, r_max = select_plateau_values(rows)
    if y.size == 0:
        return np.nan, np.nan, 0, np.nan, np.nan
    mean_val, sd_val, n_val = _mean_sd_n(y)
    return mean_val, sd_val, n_val, r_min, r_max


def compute_ellner_from_c2(c2_file, r_min, r_max, dim=M_D2):
    """Ellner extension of Takens' estimator (book eq. 8.78).

    `d_2^(E) = [C^(m)(r_max) - C^(m)(r_min)] / integral_{r_min}^{r_max} C(r)/r dr`.
    `r_min`/`r_max` are typically taken from the Takens plateau auto-detected on
    the d_2^(T)(r') curve so that they bracket the linear scaling region.
    Returns NaN if the integral cannot be evaluated.
    """
    # Ellner's extension is introduced after the book explains a weakness of the
    # raw Takens estimator: d_2^(T)(r') averages over all distances below r'.
    # If the correlation integral contains several scaling regions, including
    # every distance from 0 to r' can blur the desired region. Ellner's formula
    # solves this by restricting the estimator to a finite scaling interval:
    #
    #   d_2^(E) =
    #       [ C^(m)(r_max) - C^(m)(r_min) ]
    #       / integral_{r_min}^{r_max} C^(m)(r) / r dr                 (8.78)
    #
    # In this implementation, r_min and r_max are not hand-selected. They come
    # from the plateau of d_2^(T)(r') detected in extract_takens_plateau(). Thus
    # TAKENS and ELLNER are tied to the same observed scaling region.
    #
    # Equation (8.79) gives a standard-deviation expression for Ellner's estimate
    # using M_C(r_max) and a theta-like ratio. We do not use that theoretical
    # formula as the hypothesis-test uncertainty; instead the test uses the
    # empirical SD across stationary-bootstrap ELLNER estimates, which is the
    # quantity requested by the current supervisor-aligned testing procedure.
    #
    # Numerically, we interpolate C(r_min) and C(r_max), because the detected
    # plateau endpoints need not coincide exactly with .c2 grid points.
    rows = extract_tagged_block(c2_file, dim=dim, tag="#dim")
    if rows.size == 0:
        return np.nan
    if not (np.isfinite(r_min) and np.isfinite(r_max)) or r_min <= 0.0 or r_max <= r_min:
        return np.nan
    r = rows[:, 0]
    c = rows[:, 1]
    # The integral C(r)/r and the logarithmic scale interpretation require
    # strictly positive radii and strictly positive correlation integrals.
    finite = np.isfinite(r) & np.isfinite(c) & (r > 0.0) & (c > 0.0)
    r = r[finite]
    c = c[finite]
    if r.size < 2:
        return np.nan
    order = np.argsort(r)
    r = r[order]
    c = c[order]
    # Restrict integration to the Takens-selected plateau interval. This is the
    # key Ellner idea: use only the finite scaling region, not all distances from
    # zero up to a single r'.
    mask = (r >= r_min) & (r <= r_max)
    if int(mask.sum()) < 2:
        return np.nan
    r_sel = r[mask]
    c_sel = c[mask]
    c_max = float(np.interp(r_max, r_sel, c_sel))
    c_min = float(np.interp(r_min, r_sel, c_sel))
    if not (np.isfinite(c_max) and np.isfinite(c_min)) or c_max <= c_min:
        return np.nan
    # Trapezoidal integration is adequate here because d2.exe already gives a
    # dense, ordered grid of radius values. NumPy renamed trapz -> trapezoid in
    # recent versions, so use the new function when available.
    integrand = c_sel / r_sel
    _trapz = getattr(np, "trapezoid", np.trapz)
    integral = float(_trapz(integrand, r_sel))
    if not np.isfinite(integral) or integral <= 0.0:
        return np.nan
    return float((c_max - c_min) / integral)


MIN_LYAP_LINEAR_POINTS = 5


def _best_linear_slope(x, y, min_points=MIN_LYAP_LINEAR_POINTS):
    """Pick slope from the contiguous (x, y) window with maximal |rho|.

    Used for the Lyapunov S(t) curve: the book defines lambda_max as the slope
    of the linear part of S(t) vs t. Instead of fixing t in [2, 10), we scan
    every contiguous window of at least `min_points` and keep the slope from
    the window with the highest absolute Pearson correlation.
    """
    x = np.asarray(x, dtype=float)
    y = np.asarray(y, dtype=float)
    n = min(len(x), len(y))
    if n < min_points:
        return np.nan
    x = x[:n]
    y = y[:n]
    finite = np.isfinite(x) & np.isfinite(y)
    x = x[finite]
    y = y[finite]
    n = len(x)
    if n < min_points:
        return np.nan
    # Book connection:
    # Equation (8.94) states that nearby reconstructed states should separate
    # approximately exponentially under chaotic dynamics:
    #
    #   ||X_i(t+t0) - X_j(t+t0)|| ~= exp(lambda_max * t)
    #                                  ||X_i(t0) - X_j(t0)||
    #
    # Equation (8.95) then defines S(t) as an average log-distance growth over
    # reference states and their neighbourhoods. If an exponential-growth region
    # is present, S(t) is approximately linear in t, and the slope is lambda_max.
    #
    # The book examples show that the linear part can occupy different iteration
    # ranges for different systems and embedding dimensions. Therefore, scanning
    # every contiguous window is safer than hard-coding a fixed t interval.
    # We choose the window with the largest absolute Pearson correlation and use
    # its fitted slope as the LLE estimate.
    best_slope = np.nan
    best_rho = -np.inf
    best_width = 0
    for width in range(min_points, n + 1):
        for start in range(0, n - width + 1):
            stop = start + width
            xs = x[start:stop]
            ys = y[start:stop]
            rho = _pearson_abs(xs, ys)
            if not np.isfinite(rho):
                continue
            try:
                slope, _ = np.polyfit(xs, ys, 1)
            except Exception:
                continue
            if not np.isfinite(slope):
                continue
            if (rho, width) > (best_rho, best_width):
                best_rho = rho
                best_width = width
                best_slope = float(slope)
    return best_slope


def extract_lle_mean_std(lyap_file):
    """Largest Lyapunov estimate: slope of S(t) for the first m=3 epsilon block.

    lyap_k can output several epsilon blocks for the same embedding dimension.
    To keep LLE a single scalar, consistent with the thesis design, we take the
    first m=3 block and fit its best linear segment. There is no within-invariant
    vector here, so SD is reported as NaN and n as 1.
    """
    # The .lyap output contains blocks whose data rows are:
    #   column 1: iteration t,
    #   column 2: S(t), the averaged logarithmic stretching factor,
    #   column 3: number of contributing points.
    #
    # We use column 2 versus column 1 because equation (8.95) defines S(t), and
    # the paragraph after that equation states that the slope of the linear part
    # of S(t) is the largest Lyapunov exponent. This is why the code does not
    # average slopes over all epsilon blocks or all dimensions: the thesis uses
    # one scalar Kantz estimate for m=3.
    try:
        with open(lyap_file, "r", encoding="utf-8", errors="ignore") as handle:
            lines = handle.readlines()
        first_block = None
        current_block = []
        current_dim = None
        for line in lines:
            stripped = line.strip()
            if stripped.startswith("#epsilon"):
                # A new lyap_k block starts. If the previous block was the first
                # m=3 block with data, stop immediately; later epsilon blocks
                # are deliberately ignored.
                if current_dim == M_LYAP and current_block:
                    first_block = np.array(current_block, dtype=float)
                    break
                current_dim = None
                current_block = []
                tokens = stripped.replace("=", " ").split()
                for idx, token in enumerate(tokens):
                    if token.lower() == "dim" and idx + 1 < len(tokens):
                        try:
                            current_dim = int(float(tokens[idx + 1]))
                        except ValueError:
                            current_dim = None
                        break
                continue
            if stripped.startswith("#") or stripped == "":
                continue
            if current_dim != M_LYAP:
                continue
            parts = stripped.split()
            if len(parts) >= 2:
                current_block.append([float(parts[0]), float(parts[1])])
        if first_block is None and current_dim == M_LYAP and current_block:
            first_block = np.array(current_block, dtype=float)
        if first_block is None or first_block.size == 0 or first_block.ndim < 2:
            return np.nan, np.nan, 0
        slope = _best_linear_slope(first_block[:, 0], first_block[:, 1])
        if not np.isfinite(slope):
            return np.nan, np.nan, 0
        return slope, np.nan, 1
    except Exception:
        return np.nan, np.nan, 0


def compute_percentile_radius(
    series,
    delay=1,
    m=RQA_EMBEDDING_DIM,
    percentile=RQA_RADIUS_PERCENTILE_DEFAULT,
    max_vectors=RQA_RADIUS_MAX_VECTORS,
    seed=RQA_RADIUS_SAMPLE_SEED,
):
    """Recurrence threshold as a percentile of pairwise Euclidean distances.

    Reconstructs the (m, delay) embedded state space and returns the requested
    percentile of pairwise Euclidean distances between embedded vectors. For
    long series the embedded matrix is randomly subsampled (without replacement,
    fixed RNG seed for reproducibility) down to `max_vectors` rows to keep pdist
    memory bounded. Returns NaN when the embedding cannot be built or when
    fewer than two embedded vectors are available.
    """
    delay = int(delay) if delay and int(delay) > 0 else 1
    m = int(m) if m and int(m) > 0 else 1
    embedded = embed_series(series, delay=delay, m=m)
    if max_vectors and embedded.shape[0] > max_vectors:
        # pdist is quadratic in the number of vectors. Subsampling keeps memory
        # and runtime predictable while preserving a stable radius estimate.
        rng = np.random.default_rng(seed)
        sample_idx = rng.choice(embedded.shape[0], size=max_vectors, replace=False)
        embedded = embedded[sample_idx]
    if embedded.shape[0] < 2:
        return float("nan")
    distances = pdist(embedded, metric="euclidean")
    if distances.size == 0:
        return float("nan")
    return float(np.percentile(distances, percentile))


def effective_rqa_theiler(theiler):
    """Use at least 1 so diagonal-line RQA metrics ignore the line of identity.

    PyRQA with theiler_corrector=0 includes the main diagonal. That makes
    MAXLINE equal to the full embedded series length, which is not meaningful
    for recurrence-line diagnostics. For metrics we force at least one excluded
    diagonal while still allowing the batch recurrence plot to use its own W.
    """
    try:
        return max(1, int(theiler))
    except Exception:
        return 1


def embed_series(series, delay=1, m=RQA_EMBEDDING_DIM):
    """Construct a standard delay-embedding matrix from a scalar series.

    Row i is (x_i, x_{i+delay}, ..., x_{i+(m-1)delay}). Non-finite input values
    are dropped before embedding so downstream distance calculations do not
    propagate NaNs.
    """
    data = np.asarray(series, dtype=float)
    finite_mask = np.isfinite(data)
    if not finite_mask.all():
        data = data[finite_mask]
    delay = int(delay) if delay and int(delay) > 0 else 1
    m = int(m) if m and int(m) > 0 else 1
    span = (m - 1) * delay
    if data.size <= span:
        return np.empty((0, m), dtype=float)
    n_vec = data.size - span
    offsets = np.arange(m, dtype=np.int64) * delay
    return data[np.arange(n_vec, dtype=np.int64)[:, None] + offsets[None, :]]


def rqa_recurrence_matrix(series, delay, radius, m=RQA_EMBEDDING_DIM):
    """Build a boolean recurrence matrix for diagnostics.

    This helper is intentionally simple and explicit. It is not used for the
    core PyRQA metrics, but it is useful for manual checks and for code that
    needs a concrete recurrence matrix rather than PyRQA's internal structures.
    """
    embedded = embed_series(series, delay=delay, m=m)
    if embedded.shape[0] < 2:
        return np.zeros((0, 0), dtype=bool)
    n = embedded.shape[0]
    recurrence = np.zeros((n, n), dtype=bool)
    radius = float(radius)
    # Row-wise computation avoids constructing an N x N x m temporary array.
    for i in range(n):
        diff = embedded - embedded[i]
        recurrence[i, :] = np.sqrt(np.sum(diff * diff, axis=1)) <= radius
    return recurrence


def compute_rqa_trend(series, delay, radius, theiler=1, m=RQA_EMBEDDING_DIM):
    """RQA TREND as linear slope of recurrence density along off-LOI diagonals.

    For each diagonal distance k from the line of identity, combine the +k and
    -k diagonals and compute their recurrence density. TREND is the ordinary
    least-squares slope of that density as a function of k. Diagonals inside
    the effective Theiler window are skipped.
    """
    embedded = embed_series(series, delay=delay, m=m)
    n = embedded.shape[0]
    if n < 3:
        return np.nan
    min_k = effective_rqa_theiler(theiler)
    xs = []
    ys = []
    radius = float(radius)
    for k in range(min_k, n):
        # The +k and -k diagonals contain the same distances for a symmetric
        # recurrence matrix, so computing embedded[:-k] vs embedded[k:] captures
        # the off-identity diagonal density without materializing the full matrix.
        diff = embedded[:-k] - embedded[k:]
        if diff.size == 0:
            continue
        recurrent = np.sqrt(np.sum(diff * diff, axis=1)) <= radius
        density = float(np.mean(recurrent))
        xs.append(float(k))
        ys.append(density)
    if len(xs) < 2:
        return np.nan
    try:
        slope, _ = np.polyfit(np.asarray(xs), np.asarray(ys), 1)
    except Exception:
        return np.nan
    return float(slope)


def format_rqa_radius(radius):
    """Stable string representation used in BAT run IDs and CLI arguments.

    A fixed precision prevents tiny floating-point formatting differences from
    creating different output-folder names for the same effective radius.
    """
    if radius is None or not np.isfinite(radius):
        return f"{DEFAULT_RQA_RADIUS:.10g}"
    return f"{float(radius):.10g}"


def compute_pyrqa_metrics(series, delay, theiler, radius=None):
    """Compute PyRQA scalar metrics for the full series.

    RQA is intentionally not segmented in this pipeline. Each metric is one
    scalar for the whole original series.
    TREND is added manually because the installed PyRQA API does not expose the
    exact off-identity diagonal-density slope needed here.
    """
    r_eff = float(DEFAULT_RQA_RADIUS if radius is None else radius)
    theiler_eff = effective_rqa_theiler(theiler)
    try:
        ts = TimeSeries(series, embedding_dimension=RQA_EMBEDDING_DIM, time_delay=delay)
        settings = Settings(ts, analysis_type=Classic,
                            neighbourhood=FixedRadius(r_eff),
                            similarity_measure=EuclideanMetric,
                            theiler_corrector=theiler_eff)
        computation = RQAComputation.create(settings, verbose=False)
        result = computation.run()
        result.min_diagonal_line_length = 2
        result.min_vertical_line_length = 2
        trend = compute_rqa_trend(series, delay=delay, radius=r_eff, theiler=theiler_eff)
        return {
            "RR": float(result.recurrence_rate),
            "DET": float(result.determinism),
            "LAM": float(result.laminarity),
            "MAXLINE": float(result.longest_diagonal_line),
            "ENTR": float(result.entropy_diagonal_lines),
            "TT": float(result.trapping_time),
            "TREND": float(trend),
        }
    except Exception:
        return {k: np.nan for k in RQA_KEYS}


def compute_invariants(series_array, output_dir, label, delay, theiler,
                       metric_names, rqa_radius=None, series_std_fallback=np.nan,
                       rqa_radius_mode="percentile",
                       rqa_percentile=RQA_RADIUS_PERCENTILE_DEFAULT,
                       rqa_radius_log=None):
    """Compute invariants for an in-memory series. Returns (mean_dict, sd_dict, n_dict).

    Value / SD / n sources:
      TAKENS — plateau mean of the c2t Takens-Theiler curve d_2^(T)(r') for
               embedding m=3. Its plateau end-points also define r_min/r_max.
      ELLNER — Ellner extension (eq. 8.78) evaluated on .c2 between the same
               r_min and r_max. The reported SD/n come from the Takens plateau
               dispersion and serve as an orientation for the interval quality.
      LLE   — slope of the linear part of S(t) for m=3
      RQA   — one metric value computed on the full time series

    `series_std_fallback` (the sample SD of the analysed series, sigma) is used
    to set the `d2.exe` evaluation range to [0.25*sigma, 0.5*sigma], matching
    the book's practical Takens scale recommendation.

    For RQA, the recurrence radius is selected dynamically when
    `rqa_radius_mode == 'percentile'` (default) as `rqa_percentile`-th percentile
    of pairwise Euclidean distances between embedded state vectors. If the
    percentile calculation cannot be performed, the function falls back to the
    explicit `rqa_radius` value (or `DEFAULT_RQA_RADIUS` if that is also missing).
    """
    metric_names = list(metric_names)

    # Work out which external tools are actually needed. This matters because
    # hypothesis.py is called many times during stationary bootstrap; skipping
    # unused executables saves a lot of runtime.
    need_takens = "TAKENS" in metric_names
    need_ellner = "ELLNER" in metric_names
    need_lle = "LLE" in metric_names
    need_rqa = any(k in metric_names for k in RQA_KEYS)

    # Every in-memory pseudo-series is written to a temporary .dat file because
    # TISEAN tools are command-line programs that operate on files, not arrays.
    prefix = os.path.join(output_dir, label)
    data_file = prefix + ".dat"
    np.savetxt(data_file, series_array)

    # The three output dictionaries share the same metric keys:
    #   out     -> point estimate used in comparisons,
    #   out_std -> within-curve/plateau SD where meaningful,
    #   out_n   -> number of values behind that SD.
    #
    # For bootstrap TS decisions, the important SD is later computed across the
    # B bootstrap point estimates, not from out_std.
    out = {k: np.nan for k in metric_names}
    out_std = {k: np.nan for k in metric_names}
    out_n = {k: 0 for k in metric_names}

    try:
        d2_file = h2_file = c2_file = None
        if need_takens or need_ellner:
            # Dimension metrics share one d2.exe call. The radius range is
            # tied to the original-series sigma passed by main(), so orig,
            # reshuffle, normal, t-reference, and bootstrap pseudo-series are
            # evaluated on a comparable scale grid.
            sigma = float(series_std_fallback) if np.isfinite(series_std_fallback) else np.nan
            if np.isfinite(sigma) and sigma > 0.0:
                eps_min = 0.25 * sigma
                eps_max = 0.5 * sigma
            else:
                eps_min = eps_max = None
            d2_file, h2_file, c2_file = run_d2(
                data_file, delay, theiler, prefix,
                eps_min=eps_min, eps_max=eps_max,
            )
        if (need_takens or need_ellner) and c2_file:
            # One c2t run supplies both TAKENS and ELLNER. TAKENS uses the
            # plateau mean directly. ELLNER reuses the plateau endpoints and
            # integrates the original .c2 correlation integral over that interval.
            #
            # Book mapping in this block:
            #   1. run_c2t() gives the Takens curve d_2^(T)(r') from (8.75)-(8.76).
            #   2. extract_takens_plateau() implements the recommended plateau
            #      search in d_2^(T)(r') vs ln(r') after (8.77).
            #   3. compute_ellner_from_c2() applies Ellner's finite-interval
            #      correction (8.78) on the same scaling region.
            takens_file = prefix + "_takens.dat"
            run_c2t(c2_file, takens_file)
            takens_mean, takens_sd, n_val, r_min, r_max = extract_takens_plateau(takens_file)
            if need_takens:
                out["TAKENS"] = takens_mean
                out_std["TAKENS"] = takens_sd
                out_n["TAKENS"] = int(n_val)
            if np.isfinite(r_min) and np.isfinite(r_max) and r_max > r_min:
                ellner = compute_ellner_from_c2(c2_file, r_min, r_max)
            else:
                ellner = np.nan
            if need_ellner:
                out["ELLNER"] = ellner
                out_std["ELLNER"] = takens_sd
                out_n["ELLNER"] = int(n_val) if np.isfinite(ellner) else 0
        if need_lle:
            # LLE is one scalar slope estimate. It is recomputed for
            # original/reference/bootstrap series when LLE is selected.
            #
            # Book mapping:
            #   run_lyap_k() estimates S(t), the averaged logarithmic divergence
            #   from (8.95), under the exponential-separation model (8.94).
            #   extract_lle_mean_std() then finds the linear part of S(t) and
            #   returns its slope as lambda_max.
            lyap_file = prefix + "_lyap.txt"
            run_lyap_k(data_file, delay, lyap_file)
            mu, sg, nn = extract_lle_mean_std(lyap_file)
            out["LLE"], out_std["LLE"] = mu, sg
            out_n["LLE"] = nn
        if need_rqa:
            # Radius selection is per analysed series by default. The same code
            # path is used by RQA.bat and direct hypothesis.py calls.
            r_eff = None
            source = "fixed"
            if str(rqa_radius_mode).lower() == "percentile":
                r_eff = compute_percentile_radius(
                    series_array,
                    delay=delay,
                    m=RQA_EMBEDDING_DIM,
                    percentile=rqa_percentile,
                )
                source = f"percentile({rqa_percentile:g}%)"
                if not (np.isfinite(r_eff) and r_eff > 0.0):
                    r_eff = None
                    source = "fixed (percentile failed)"
            if r_eff is None:
                # Fallback order: explicit --rqa_radius if valid, otherwise the
                # module default. This keeps RQA robust when the percentile
                # cannot be computed (for example very short series).
                r_eff = (
                    float(rqa_radius)
                    if rqa_radius is not None and np.isfinite(rqa_radius) and rqa_radius > 0.0
                    else float(DEFAULT_RQA_RADIUS)
                )
            print(
                f"     RQA radius for label={label}: r={r_eff:.6g}  "
                f"({source}, m={RQA_EMBEDDING_DIM}, tau={delay})"
            )
            if isinstance(rqa_radius_log, dict):
                rqa_radius_log[label] = {"radius": float(r_eff), "source": source}
            rqa_values = compute_pyrqa_metrics(series_array, delay, theiler, r_eff)
            for k in RQA_KEYS:
                if k in out:
                    value = float(rqa_values.get(k, np.nan))
                    out[k] = value
                    out_std[k] = np.nan
                    out_n[k] = 1 if np.isfinite(value) else 0
    except subprocess.CalledProcessError:
        logger.exception("TISEAN failed for label=%s", label)
    except Exception:
        logger.exception("Error computing invariants for label=%s", label)
    finally:
        # Each bootstrap iteration writes several temporary files. Remove every
        # file sharing the prefix so long runs do not fill the result directory.
        for tmp in glob.glob(prefix + "*"):
            try:
                os.remove(tmp)
            except OSError:
                pass

    return out, out_std, out_n


def parse_metrics_list(raw_metrics):
    """Normalize and validate a comma-separated CLI metric list."""
    tokens = [t.strip().upper() for t in str(raw_metrics).split(",") if t.strip()]
    if not tokens:
        raise ValueError("metrics list is empty")
    invalid = [t for t in tokens if t not in ALL_METRICS]
    if invalid:
        raise ValueError(f"unknown metric(s): {', '.join(invalid)}")
    return list(dict.fromkeys(tokens))


def metric_names_for_scope(_=None):
    # Direct dimension-hypothesis runs default to Ellner only. Batch scripts
    # that need LLE/RQA pass an explicit --metrics_list.
    return ["ELLNER"]


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    # ------------------------------------------------------------------
    # CLI contract
    # ------------------------------------------------------------------
    #
    # hypothesis.py is designed to be called from several Windows batch files
    # with different metric scopes:
    #   correlation_dimension.bat -> ELLNER by default, or TAKENS/ELLNER switch
    #   Lambda_max.bat           -> LLE
    #   RQA.bat                  -> RQA metric list + recurrence radius
    #
    # Direct calls without --metrics_list default to ["ELLNER"]. That default is
    # deliberate: the current thesis dimension hypothesis is Ellner-first, while
    # TAKENS remains available through --metrics_list TAKENS or TAKENS,ELLNER.
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", required=True)
    parser.add_argument("--base", required=True)
    parser.add_argument("--delay", type=int, required=True)
    parser.add_argument("--theiler", type=int, required=True)
    parser.add_argument("--output_dir", required=True)
    parser.add_argument("--test_mode", default="false")
    parser.add_argument("--metrics", default="full")
    parser.add_argument("--metrics_list", default="")
    parser.add_argument("--bootstrap_samples", type=int, default=DEFAULT_BOOTSTRAP_SAMPLES)
    parser.add_argument(
        "--stationary_block_mean",
        type=float,
        default=DEFAULT_STATIONARY_BLOCK_MEAN,
        help="Mean stationary-bootstrap block length. <=0 uses sqrt(n).",
    )
    parser.add_argument("--ts_threshold", type=float, default=DEFAULT_TS_THRESHOLD)
    parser.add_argument("--rqa_radius", type=float, default=DEFAULT_RQA_RADIUS)
    parser.add_argument(
        "--rqa_radius_mode",
        choices=["percentile", "fixed"],
        default="percentile",
        help=(
            "How to select PyRQA recurrence radius. "
            "'percentile' (default): use the --rqa_percentile-th percentile of pairwise "
            "Euclidean distances between embedded state vectors of the analysed series; "
            "fall back to --rqa_radius if the percentile cannot be computed. "
            "'fixed': always use --rqa_radius."
        ),
    )
    parser.add_argument(
        "--rqa_percentile",
        type=float,
        default=RQA_RADIUS_PERCENTILE_DEFAULT,
        help="Percentile (in %%) of pairwise distances used as RQA radius when --rqa_radius_mode=percentile.",
    )
    args = parser.parse_args()

    # Fail early on invalid scalar parameters. These checks catch batch-script
    # wiring mistakes before a long TISEAN/bootstrap run starts.
    if args.rqa_radius <= 0.0:
        raise SystemExit("hypothesis.py: --rqa_radius must be positive.")
    if not (0.0 < args.rqa_percentile < 100.0):
        raise SystemExit("hypothesis.py: --rqa_percentile must be in (0, 100).")
    if args.bootstrap_samples < 1:
        raise SystemExit("hypothesis.py: --bootstrap_samples must be >= 1.")
    if args.ts_threshold <= 0:
        raise SystemExit("hypothesis.py: --ts_threshold must be positive.")

    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s | %(levelname)s | %(name)s | %(message)s",
        datefmt="%H:%M:%S",
    )

    os.makedirs(args.output_dir, exist_ok=True)

    # Resolve the metric scope after CLI validation. When a batch file passes an
    # explicit list, that list is authoritative; otherwise use the direct-run
    # default from metric_names_for_scope().
    metric_names = (
        parse_metrics_list(args.metrics_list)
        if args.metrics_list.strip()
        else metric_names_for_scope(args.metrics)
    )

    print(f"  -> Stationary-bootstrap hypothesis test: {args.base}")
    print(f"     tau={args.delay}, W={args.theiler}, "
          f"metrics={','.join(metric_names)}")
    block_mean_label = "sqrt(n)" if args.stationary_block_mean <= 0 else f"{args.stationary_block_mean:g}"
    print(
        f"     Bootstrap TS test: B={args.bootstrap_samples}, "
        f"stationary_block_mean={block_mean_label}, threshold=|TS|>{args.ts_threshold:g}"
    )
    if args.rqa_radius_mode == "percentile":
        print(
            f"     RQA radius mode: percentile (p={args.rqa_percentile:g}%, "
            f"m={RQA_EMBEDDING_DIM}, tau={args.delay}); "
            f"fallback fixed radius = {args.rqa_radius:g}"
        )
    else:
        print(f"     RQA radius mode: fixed (r={args.rqa_radius:g})")

    # ------------------------------------------------------------------
    # 1. Load original log-returns; estimate mu and sigma of the series
    # ------------------------------------------------------------------
    #
    # mu_r and sigma_r serve two purposes:
    #   * generate the Gaussian and Student-t descriptive references,
    #   * define the d2.exe radius range for all dimension recomputations.
    orig_data = load_data(args.input)
    n = len(orig_data)
    mu_r = float(np.mean(orig_data))
    sigma_r = float(np.std(orig_data, ddof=1))
    print(f"  -> Original series: n={n}, mu={mu_r:.6f}, sigma={sigma_r:.6f}")

    # ------------------------------------------------------------------
    # 2. Generate surrogate (randperm) and two reference series
    # ------------------------------------------------------------------
    #
    # The reshuffled series is the actual null comparison in the TS statistic.
    # Normal and t(3.5) are kept as Step 0 descriptive benchmarks so the thesis
    # tables can compare the original against several noise shapes.
    surr_data = generate_single_surrogate(orig_data)
    norm_data = generate_normal_series(mu_r, sigma_r, n)
    t_data = generate_t_series(mu_r, sigma_r, n, dof=T_DOF)

    series_specs = [
        ("orig",   orig_data),
        ("surr",   surr_data),
        ("normal", norm_data),
        (f"t{T_DOF}", t_data),
    ]

    # ------------------------------------------------------------------
    # 3. Compute invariants for original and reference series
    # ------------------------------------------------------------------
    #
    # For null/reference series, recompute only metrics listed in
    # NULL_SERIES_METRICS. This prevents expensive and methodologically invalid
    # recomputation of scalar-only RQA values for synthetic references.
    tmp_dir = os.path.join(args.output_dir, "tmp_hyp")
    os.makedirs(tmp_dir, exist_ok=True)

    results = {}   # label -> {metric: mean invariant value}
    stds    = {}   # label -> {metric: SD of invariant values}
    counts  = {}   # label -> {metric: n values used for SD}
    rqa_radius_log = {}  # label -> {radius, source}
    bootstrap_metrics = [m for m in metric_names if m in BOOTSTRAP_TEST_METRICS]
    bootstrap_values = {m: [] for m in bootstrap_metrics}
    bootstrap_mean = {m: np.nan for m in metric_names}
    bootstrap_sd = {m: np.nan for m in metric_names}
    bootstrap_n = {m: 0 for m in metric_names}

    for label, series in series_specs:
        # Original series gets the full requested scope. Synthetic reference
        # series get only the metrics that are meaningful for Step 0 and TS.
        metrics_for_label = (
            metric_names
            if label == "orig"
            else [m for m in metric_names if m in NULL_SERIES_METRICS]
        )

        if metrics_for_label:
            print(f"  -> Computing invariants for series: {label} ({','.join(metrics_for_label)}) ...")
            inv_part, inv_std_part, inv_n_part = compute_invariants(
                series, tmp_dir, f"{args.base}_{label}",
                args.delay, args.theiler, metrics_for_label, args.rqa_radius,
                series_std_fallback=sigma_r,
                rqa_radius_mode=args.rqa_radius_mode,
                rqa_percentile=args.rqa_percentile,
                rqa_radius_log=rqa_radius_log,
            )
        else:
            print(f"  -> Skipping invariant recomputation for series: {label} (not needed for selected metrics).")
            inv_part, inv_std_part, inv_n_part = {}, {}, {}

        results[label] = {k: inv_part.get(k, np.nan) for k in metric_names}
        stds[label]    = {k: inv_std_part.get(k, np.nan) for k in metric_names}
        counts[label]  = {k: inv_n_part.get(k, 0) for k in metric_names}

    if bootstrap_metrics:
        # Stationary bootstrap preserves local time dependence by resampling
        # geometrically distributed blocks. Each pseudo-series is passed through
        # exactly the same invariant computation as the original.
        mean_block_length = None if args.stationary_block_mean <= 0 else args.stationary_block_mean
        print(
            f"  -> Stationary bootstrap for {','.join(bootstrap_metrics)}: "
            f"B={args.bootstrap_samples}, mean_block_length={block_mean_label}"
        )
        boot_series = stationary_bootstrap_samples(
            orig_data,
            args.bootstrap_samples,
            mean_block_length=mean_block_length,
            seed=0,
        )
        for idx, boot_data in enumerate(boot_series, start=1):
            print(
                f"     bootstrap {idx:03d}/{args.bootstrap_samples}: "
                f"computing {','.join(bootstrap_metrics)} ..."
            )
            inv_part, _inv_std_part, _inv_n_part = compute_invariants(
                boot_data,
                tmp_dir,
                f"{args.base}_statboot_{idx:03d}",
                args.delay,
                args.theiler,
                bootstrap_metrics,
                args.rqa_radius,
                series_std_fallback=sigma_r,
                rqa_radius_mode=args.rqa_radius_mode,
                rqa_percentile=args.rqa_percentile,
            )
            for metric in bootstrap_metrics:
                value = inv_part.get(metric, np.nan)
                if np.isfinite(value):
                    bootstrap_values[metric].append(float(value))

        # Convert the bootstrap cloud of invariant estimates into the robust
        # centre and spread used by the TS statistic.
        for metric in bootstrap_metrics:
            arr = np.asarray(bootstrap_values[metric], dtype=float)
            arr = arr[np.isfinite(arr)]
            bootstrap_n[metric] = int(arr.size)
            if arr.size:
                bootstrap_mean[metric] = float(np.mean(arr))
            if arr.size > 1:
                bootstrap_sd[metric] = float(np.std(arr, ddof=1))

    try:
        os.rmdir(tmp_dir)
    except OSError:
        pass

    # ------------------------------------------------------------------
    # 4. Bootstrap TS test: stationary bootstrap centre/SD vs reshuffle
    # ------------------------------------------------------------------
    #
    # TAKENS/ELLNER/LLE receive a TS decision. All scalar-only RQA metrics are
    # marked "not bootstrap-tested" so downstream tables can distinguish
    # unavailable tests from failed rejections.
    test_stats = {}
    abs_test_stats = {}
    decisions = {}

    for metric in metric_names:
        if metric in BOOTSTRAP_TEST_METRICS:
            ts, abs_ts, dec = invariant_bootstrap_ts_test(
                bootstrap_mean.get(metric, np.nan),
                bootstrap_sd.get(metric, np.nan),
                results["surr"].get(metric, np.nan),
                args.ts_threshold,
            )
            test_stats[metric] = ts
            abs_test_stats[metric] = abs_ts
            decisions[metric] = dec
        else:
            test_stats[metric] = np.nan
            abs_test_stats[metric] = np.nan
            decisions[metric] = "not bootstrap-tested"

    # ------------------------------------------------------------------
    # 5. Write human- and parser-readable summary
    # ------------------------------------------------------------------
    #
    # The text format is intentionally simple: print_results.py parses these
    # fixed-width rows to build per-folder aggregate summaries, while documents.py
    # uses those aggregates for Word tables.
    labels_ordered = [lbl for lbl, _ in series_specs]

    summary_file = os.path.join(args.output_dir, f"{args.base}_surrogate_summary.txt")
    with open(summary_file, "w", encoding="utf-8") as fh:
        fh.write(f"Stationary-bootstrap hypothesis test ({args.base})\n")
        fh.write(
            f"Parameters: tau={args.delay}, W={args.theiler}, B={args.bootstrap_samples}, "
            f"stationary_block_mean={block_mean_label}, TS_threshold={args.ts_threshold:g}, "
            f"metrics={','.join(metric_names)}, T_dof={T_DOF}\n"
        )
        fh.write(f"Original series: n={n}, mu_r={mu_r:.6f}, sigma_r={sigma_r:.6f}\n")
        if args.rqa_radius_mode == "percentile":
            fh.write(
                f"RQA radius mode: percentile (p={args.rqa_percentile:g}%, m={RQA_EMBEDDING_DIM}, "
                f"tau={args.delay}); fallback fixed radius = {args.rqa_radius:g}\n"
            )
        else:
            fh.write(f"RQA radius mode: fixed (r={args.rqa_radius:g})\n")
        if rqa_radius_log:
            for lbl, info in rqa_radius_log.items():
                fh.write(
                    f"  RQA radius applied to {lbl}: r={info['radius']:.6g}  ({info['source']})\n"
                )
        fh.write(
            "Surrogate: randperm (full random permutation, no blocking).\n"
            "Normal:    N(mu_r, sigma_r) of same length.\n"
            f"t-series:  t(dof={T_DOF}) scaled to (mu_r, sigma_r) of same length.\n"
            "Stationary bootstrap: B pseudo-series from the original, with geometric block lengths.\n"
            "Reference invariants are recomputed for TAKENS/ELLNER/LLE; RQA remains original-only scalar.\n"
        )
        fh.write(
            "Test: TS=(mean_bootstrap(invariant)-invariant_reshuffle)/SD_bootstrap(invariant).\n"
            f"  Decision: reject H0 if |TS| > {args.ts_threshold:g}; this indicates structure/memory as a prerequisite for chaos, not proof of chaos.\n"
            "  Normal and t-series are reported as reference benchmarks, not as the main test pair.\n"
            "Invariant value sources:\n"
            "  TAKENS — mean of the stable plateau of the c2t Takens-Theiler curve d_2^(T)(r') for m=3\n"
            "  ELLNER — Ellner extension (eq. 8.78) computed from .c2 over [r_min, r_max] auto-detected\n"
            "           from the same Takens plateau; reported SD is the Takens-plateau dispersion\n"
            "           (orientation of the interval quality).\n"
            "  LLE   — one slope of S(t) from the first m=3 lyap_k epsilon block\n"
            "  RQA   — one value computed on the full time series; bootstrap TS test is unavailable\n\n"
        )

        # --- Series statistics header ---
        # These are statistics of the input series themselves, not uncertainty
        # estimates of the invariants.
        fh.write("Series statistics (mean and SD of each series):\n")
        fh.write(f"  {'series':<10}  {'mean':>12}  {'sd':>12}\n")
        fh.write(f"  {'-'*38}\n")
        for label, series in series_specs:
            fh.write(f"  {label:<10}  {np.mean(series):>12.6f}  {np.std(series, ddof=1):>12.6f}\n")
        fh.write("\n")

        col_w = 12

        def _f(v):
            return f"{v:>{col_w}.4f}" if np.isfinite(v) else f"{'nan':>{col_w}}"

        if any(m in BOOTSTRAP_TEST_METRICS for m in metric_names):
            # Step 0 is a descriptive sanity check: original value against three
            # noise/reference constructions. The formal decision is still TS.
            fh.write("Step 0 invariant comparison against noise references:\n")
            fh.write(
                f"  {'Invariant':<12}  {'orig':>{col_w}}  {'resh':>{col_w}}  "
                f"{'normal':>{col_w}}  {f't{T_DOF}':>{col_w}}\n"
            )
            fh.write(f"  {'-'*66}\n")
            for metric in metric_names:
                if metric not in BOOTSTRAP_TEST_METRICS:
                    continue
                fh.write(
                    f"  {metric:<12}  {_f(results['orig'].get(metric, np.nan))}  "
                    f"{_f(results['surr'].get(metric, np.nan))}  "
                    f"{_f(results['normal'].get(metric, np.nan))}  "
                    f"{_f(results[f't{T_DOF}'].get(metric, np.nan))}\n"
                )
            fh.write(
                "  Interpretation: compare original invariant values directly with reshuffle, Gaussian, and t(3.5) references.\n\n"
            )

        # --- Invariant values table ---
        # This is the primary machine-parsed table. Keep column order stable
        # unless print_results.py is updated at the same time.
        hdr_parts = [
            f"{'Invariant':<12}",
            f"{'boot_mean':>{col_w}}",
            f"{'boot_sd':>{col_w}}",
            f"{'B':>{6}}",
        ]
        for lbl in labels_ordered:
            hdr_parts.append(f"{lbl:>{col_w}}")
        hdr_parts += [f"{'TS':>{col_w}}", f"{'abs_TS':>{col_w}}", f"{'decision':<26}"]
        hdr = "  " + "  ".join(hdr_parts)
        fh.write(hdr + "\n")
        fh.write("  " + "-" * (len(hdr) - 2) + "\n")

        print(f"\n  --- Invariant table ---")
        print(f"  {hdr.strip()}")
        print(f"  {'-' * (len(hdr) - 2)}")

        for metric in metric_names:
            bm = bootstrap_mean.get(metric, np.nan)
            bs = bootstrap_sd.get(metric, np.nan)
            bn = bootstrap_n.get(metric, 0)
            row_parts = [f"{metric:<12}", _f(bm), _f(bs), f"{bn:>6}"]
            for lbl in labels_ordered:
                row_parts.append(_f(results[lbl][metric]))
            row_parts.append(_f(test_stats[metric]))
            row_parts.append(_f(abs_test_stats[metric]))
            row_parts.append(f"  {decisions[metric]:<26}")
            row = "  " + "  ".join(row_parts)
            fh.write(row + "\n")
            print(f"  {row.strip()}")

        # --- Conclusion ---
        # Repeat decisions in a compact block for quick console reading.
        fh.write(f"\nConclusion (TS threshold={args.ts_threshold:g}):\n")
        print(f"\n  Conclusion (TS threshold={args.ts_threshold:g}):")
        for metric in metric_names:
            line = f"  {metric:<10}: {decisions[metric]}"
            fh.write(line + "\n")
            print(line)

    print(f"\n  -> Summary written to {summary_file}")


if __name__ == "__main__":
    main()