"""TISEAN subprocess wrappers and tagged-block parsers."""

import os
import shutil
import subprocess

import numpy as np

from hypothesis_config import (
    D2_DIAGNOSTIC_M_MAX,
    D2_EPSILON_STEPS,
    D2_PAIR_LIMIT,
    M_D2,
    M_LYAP,
    lyap_k_steps,
    lyap_min_neighbors,
)
from surrogate_sampling import load_series_1d

# ---------------------------------------------------------------------------
# TISEAN command wrappers and low-level parsers
# ---------------------------------------------------------------------------
#
# This project relies on external TISEAN executables for the heavy nonlinear
# time-series routines. The wrappers below keep all subprocess invocation details
# in one place so higher-level invariant code can work with normal Python files:
#
# * run_d2 writes .d2, .h2 and .c2 outputs from one call.
# * run_c2t transforms the .c2 correlation integral into Takens curves.
# * run_lyap_k writes Kantz S(t) divergence curves for LLE extraction.
#
# Parser helpers are intentionally tolerant: TISEAN files contain metadata lines,
# empty lines, and multiple indexed blocks. When parsing fails, the function
# returns an empty array/NaN and lets the caller mark that invariant unavailable.

def load_data(filename):
    """Load one-column log-return data through the shared sampling helper."""
    return load_series_1d(filename)


def resolve_tool(tool_name):
    """Resolve a TISEAN executable without hard-coding one installation path.

    Resolution order:
      1. TISEAN_BIN environment variable,
      2. repository-local Tisean_3.0.0/bin directory,
      3. PATH lookup, with and without the Windows .exe suffix.

    Keeping this flexible is important because the code is used both from
    Windows batch scripts and from direct Python smoke tests.
    """
    from_env = os.environ.get("TISEAN_BIN")
    if from_env:
        candidate = os.path.join(from_env, f"{tool_name}.exe")
        if os.path.exists(candidate):
            return candidate
    local_bin = os.path.join(
        os.path.dirname(os.path.abspath(__file__)),
        "Tisean_3.0.0", "bin", f"{tool_name}.exe",
    )
    if os.path.exists(local_bin):
        return local_bin
    which = shutil.which(tool_name)
    if which:
        return which
    which_exe = shutil.which(f"{tool_name}.exe")
    if which_exe:
        return which_exe
    raise FileNotFoundError(f"TISEAN executable for '{tool_name}' was not found.")


def run_d2(data_file, delay, theiler, output_prefix):
    """Run TISEAN d2.exe on its default radius scan.

    d2.exe sweeps m = 1 .. D2_DIAGNOSTIC_M_MAX so plots can show the full
    saturation pattern, but TAKENS / ELLNER are extracted only from the
    m = M_D2 block (see ``invariants_correlation.extract_takens_plateau``).
    """
    # `d2.exe` is the common source for the current dimension path:
    # .c2 -> Takens and Ellner dimension estimates,
    # .h2 -> generated by TISEAN but no longer consumed by hypothesis.py,
    # .d2 -> local-slope diagnostic plots only.
    cmd = [resolve_tool("d2"), f"-d{delay}", f"-M1,{D2_DIAGNOSTIC_M_MAX}",
           f"-t{theiler}",
           f"-#{D2_EPSILON_STEPS}", f"-N{D2_PAIR_LIMIT}"]
    cmd += ["-o", output_prefix, data_file]
    subprocess.run(cmd, check=True, capture_output=True, text=True)
    return output_prefix + ".d2", output_prefix + ".h2", output_prefix + ".c2"


def run_c2t(c2_file, output_file):
    """Run TISEAN c2t using relative paths to avoid FORTRAN path-length limits."""
    # The Windows TISEAN build uses old FORTRAN fixed-length path buffers.
    # Running from the output directory and passing basenames avoids silent
    # truncation for long thesis result paths.
    #
    # Methodological role:
    # c2t converts the correlation integral C^(m)(r) from .c2 into Takens'
    # maximum-likelihood correlation-dimension curve d_2^(T)(r'), i.e. the
    # practical form of the book's equations (8.75)-(8.76). This script does not
    # implement the all-pairs Takens average directly; it delegates that part to
    # TISEAN and then selects a stable plateau from the resulting curve.
    cwd = os.path.dirname(os.path.abspath(c2_file))
    cmd = [
        resolve_tool("c2t"),
        "-V0",
        "-o",
        os.path.basename(output_file),
        os.path.basename(c2_file),
    ]
    subprocess.run(cmd, cwd=cwd, check=True, capture_output=True, text=True)
    return output_file


def run_lyap_k(data_file, delay, theiler, output_file):
    # Kantz / largest-Lyapunov setup (matches Lambda_max.bat):
    #
    #   lyap_k -d<tau> -m3 -M3 -t<W> -n500 -s10 -o <out> <data>
    #
    # TISEAN excludes pairs with |i-j| <= W (strict > W for inclusion), same as
    # d2.exe -t. ``theiler`` is the per-coin W_D2_<sym> from theilers_w.bat.
    try:
        w_eff = max(0, int(theiler))
    except (TypeError, ValueError):
        w_eff = 0
    cmd = [
        resolve_tool("lyap_k"),
        f"-d{delay}",
        f"-m{M_LYAP}",
        f"-M{M_LYAP}",
        f"-t{w_eff}",
        "-n",
        str(lyap_k_steps()),
        "-s",
        str(lyap_min_neighbors()),
        "-o",
        output_file,
        data_file,
    ]
    subprocess.run(cmd, check=True, capture_output=True, text=True)


def extract_tagged_block(path, dim=M_D2, tag="#dim"):
    """Read a two-column block identified by '#dim=' or '#m=' from TISEAN outputs.

    TISEAN outputs usually contain several blocks:
      * .c2/.d2/.h2 label embedding blocks as "#dim=<m>",
      * c2t labels Takens blocks as "#m=<m>".

    The first column is always the scale r (or r'), and the second column is the
    metric value at that scale. Higher columns, if present, are ignored here.

    On parse failure returns an empty array; callers must treat empty/NaN as
    "invariant unavailable" (see :func:`hypothesis_ts.invariant_bootstrap_ts_test`).
    """
    rows = []
    current_dim = None
    try:
        with open(path, "r", encoding="utf-8", errors="ignore") as handle:
            for line in handle:
                stripped = line.strip()
                if not stripped:
                    continue
                if stripped.startswith(tag):
                    try:
                        current_dim = int(stripped.split("=")[1].strip())
                    except (ValueError, IndexError):
                        current_dim = None
                    continue
                if stripped.startswith("#") or stripped.startswith("!"):
                    continue
                if current_dim != dim:
                    continue
                parts = stripped.split()
                if len(parts) < 2:
                    continue
                try:
                    rows.append((float(parts[0]), float(parts[1])))
                except ValueError:
                    continue
    except Exception:
        return np.empty((0, 2), dtype=float)
    return np.array(rows, dtype=float)